void set_payroll(int v);
int  get_payroll(void);
int get_seconds();
void set_seconds(int v);
int get_sw();
void set_displays(int display_number, int value);
void reset_disp();
void waitForButton();
typedef enum { CMD_PUSH, CMD_DEAL, CMD_EVAL } Command;
extern volatile int buttonIsPushed;
int get_btn();
void reset_btn();
void printPayroll();